### ISSUE TITLE
Provide more thorough default styles for all file types

### ISSUE THREAD

**Issue by Octobug** [pixelunion/react-file-icon#8]
![image](https://user-images.githubusercontent.com/8007022/38368847-f8fab4a8-3918-11e8-8035-2405c6828fae.png)

It's a little bit tedious to specify styles for different type icon. These styles are good enough. Is it possible to use this component like: 

```javascript
files.map(file => {
    return (
        <FileIcon
            size={48}
            extension="{file.extension}"
        />
    );
});
```

Then represents its default styles.

**Comment by corygibbons** [comment]
Hey @Octobug, I've exported some default styles which should help you with this.
In the past the way we've handled this is by wrapping `FileIcon` in our own enhanced component which took care of providing default styles.

You should he able to achieve what you want with something like this:

```jsx
import FileIcon, { defaultStyles } from 'react-file-icon';

const EnhancedFileIcon = ({ ext }) => {
  // Replace or merge your own defaults into the provided `defaultStyles` if necessary

  return (
    <FileIcon extension={ext} {...defaultStyles[ext]} />
  );
};

```

```jsx
<EnhancedFileIcon ext="docx" />
```

**Comment by Octobug** [comment]
@corygibbons
Nice work!
